config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  resources :events, only: [:index, :show, :create, :update]
  resources :my_created_events, only: [:index, :edit, :update, :destroy]
  resources :subscriptions, only: [:create, :update, :destroy]

  resources :days, only: :show

  resource :admin_dashboard, only: :show
  resource :admin_login, only: :show

  namespace :admin_dashboard do
    resources :events, only: [:index, :edit, :destroy], controller: 'events'
    resources :admins, except: :show, controller: 'admins'
    resources :subscriptions, only: [:index, :edit, :destroy], controller: 'subscriptions'
    resource :site, only: [:edit, :update], controller: 'site'
  end


  root "events#index"
end

app/controllers/admin_dashboard/admins_controller.rb
module AdminDashboard
  class AdminsController < ApplicationController

    def index
      @admins = Admin.all
    end

    def new
      @admin = Admin.new
    end

    def edit
      @admin = current_admin
    end

    def create
      Admin.create(admin_params)
      redirect_to admin_dashboard_admins_path
    end

    def update
      current_admin.update(admin_params)
      bypass_sign_in(current_admin)
      redirect_to admin_dashboard_admins_path
    end

    private

    def admin_params
      params.require(:admin).permit(:email, :password)
    end

  end
end

app/controllers/admin_dashboard/application_controller.rb
module AdminDashboard
  class ApplicationController < ::ApplicationController

    before_action ->{ redirect_to admin_login_path if !signed_in? }

  end
end

app/controllers/admin_dashboard/events_controller.rb
module AdminDashboard
  class EventsController < ApplicationController

    def index
      @events = Event.order("deleted ASC NULLS FIRST, starts_at")
    end

    def edit
      @event = Event.find(params[:id])
    end

    def destroy
      Event.find(params[:id]).update(deleted: true)
      redirect_to admin_dashboard_events_path
    end

    private

    def event_params
      fields = [
        :title, :description, :starts_at, :ends_at, :venue_name, :venue_address, :venue_url,
        :sponsor_name, :sponsor_url, :tickets_price, :tickets_details, :tickets_url, :contact_name, :contact_details
      ]
      params.require(:event).permit(fields)
    end

  end
end

app/controllers/admin_dashboard/site_controller.rb
module AdminDashboard
  class SiteController < ApplicationController

    def edit
      @site = Site.first
    end

    def update
      Site.first.update(site_params)
      redirect_to edit_admin_dashboard_site_path
    end

    private

    def site_params
      params.require(:site).permit(:name, :support_email)
    end

  end
end

app/controllers/admin_dashboard/subscriptions_controller.rb
module AdminDashboard
  class SubscriptionsController < ApplicationController

    before_action :load_subscription, only: [:edit, :destroy]

    def index
      @subscriptions = Subscription.order(:duration, :created_at)
    end

    def edit      
    end

    def destroy
      @subscription.destroy
      redirect_to admin_dashboard_subscriptions_path
    end

    private

    def load_subscription
      @subscription = Subscription.find(params[:id])
    end

  end
end

app/controllers/admin_dashboards_controller.rb
class AdminDashboardsController < ApplicationController

  def show
    redirect_to admin_dashboard_events_path
  end
end

app/views/admin_dashboards/_login.html.erb
<%= form_for(:admin, :url => session_path(:admin)) do |f| %>
  
  <div>
    <label>Email</label>
    <%= f.text_field :email %>
  </div>
  <div>
    <label>Password</label>
    <%= f.password_field :password %>
  </div>
  <%= f.submit 'Sign in', class: "btn btn-primary" %>
<% end %>

app/views/admin_dashboards/_nav_links.html.erb
<div class="row">
  <ul class="nav navbar-nav">
    <li class="nav-item">
      <%= link_to "Events", admin_dashboard_events_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Admins", admin_dashboard_admins_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Subscriptions", admin_dashboard_subscriptions_path, class: "nav-link" %>
    </li>
        <li class="nav-item">
      <%= link_to "Site", edit_admin_dashboard_site_path, class: "nav-link" %>
    </li>
  </ul>
</div>