config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  resources :events, only: [:index, :show, :create, :update]
  resources :my_created_events, only: [:index, :edit, :update, :destroy]
  resources :subscriptions, only: [:create, :update, :destroy]

  resources :days, only: :show

  resource :admin_dashboard, only: :show
  resource :admin_login, only: :show

  namespace :admin_dashboard do
    resources :events, only: [:index, :edit, :destroy], controller: 'events'
    resources :admins, except: :show, controller: 'admins'
    resources :subscriptions, only: [:index, :edit, :destroy], controller: 'subscriptions'
    resource :site, only: [:edit, :update], controller: 'site'
  end


  root "events#index"
end

app/controllers/admin_dashboard/admins_controller.rb
module AdminDashboard
  class AdminsController < ApplicationController

    def index
      @admins = Admin.all
    end

    def new
      @admin = Admin.new
    end

    def edit
      @admin = current_admin
    end

    def create
      Admin.create(admin_params)
      redirect_to admin_dashboard_admins_path
    end

    def update
      current_admin.update(admin_params)
      bypass_sign_in(current_admin)
      redirect_to admin_dashboard_admins_path
    end

    private

    def admin_params
      params.require(:admin).permit(:email, :password)
    end

  end
end

app/controllers/admin_dashboard/application_controller.rb
module AdminDashboard
  class ApplicationController < ::ApplicationController

    before_action ->{ redirect_to admin_login_path if !signed_in? }

  end
end

app/controllers/admin_dashboard/events_controller.rb
module AdminDashboard
  class EventsController < ApplicationController

    def index
      @events = Event.order("deleted ASC NULLS FIRST, starts_at")
    end

    def edit
      @event = Event.find(params[:id])
    end

    def destroy
      Event.find(params[:id]).update(deleted: true)
      redirect_to admin_dashboard_events_path
    end

    private

    def event_params
      fields = [
        :title, :description, :starts_at, :ends_at, :venue_name, :venue_address, :venue_url,
        :sponsor_name, :sponsor_url, :tickets_price, :tickets_details, :tickets_url, :contact_name, :contact_details
      ]
      params.require(:event).permit(fields)
    end

  end
end

app/controllers/admin_dashboard/site_controller.rb
module AdminDashboard
  class SiteController < ApplicationController

    def edit
      @site = Site.first
    end

    def update
      Site.first.update(site_params)
      redirect_to edit_admin_dashboard_site_path
    end

    private

    def site_params
      params.require(:site).permit(:name, :support_email)
    end

  end
end

app/controllers/admin_dashboard/subscriptions_controller.rb
module AdminDashboard
  class SubscriptionsController < ApplicationController

    before_action :load_subscription, only: [:edit, :destroy]

    def index
      @subscriptions = Subscription.order(:duration, :created_at)
    end

    def edit      
    end

    def destroy
      @subscription.destroy
      redirect_to admin_dashboard_subscriptions_path
    end

    private

    def load_subscription
      @subscription = Subscription.find(params[:id])
    end

  end
end

app/controllers/admin_dashboards_controller.rb
class AdminDashboardsController < ApplicationController

  def show
    redirect_to admin_dashboard_events_path
  end
end

app/views/admin_dashboard/admins/_form.html.erb
<div class="admin-form">
  <%= simple_form_for @admin, url: @admin.persisted? ? admin_dashboard_admin_path : admin_dashboard_admins_path do |f| %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.submit nil, class: "btn btn-primary btn-submit" %>
  <% end %>
</div>

app/views/admin_dashboard/admins/_list.html.erb
<h4>Site Administrators</h4>
<table>
  <tr>
    <th>Email</th>
    <th></th>
  </tr>

  <% @admins.each do |admin| %>
    <tr>
      <td><%= admin.email %></td>
      <td>
        <% if admin == current_admin %>
          <%= link_to "Edit", edit_admin_dashboard_admin_path(current_admin), class: "btn btn-sm btn-primary" %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin_dashboard/admins/edit.html.erb
<%= render "admin_dashboards/nav_links" %>
<%= render "form" %>

app/views/admin_dashboard/admins/index.html.erb
<div id="dashboard-admins" class="dashboard">
  <%= render "admin_dashboards/nav_links" %>
  <%= link_to "New Admin", new_admin_dashboard_admin_path, class: "btn btn-sm btn-danger" %>
  <%= render "list" %>
</div>

app/views/admin_dashboard/admins/new.html.erb
<%= render "form" %>